/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::cmp::Ordering;
use core::mem;
pub enum QuantizerOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Quantizer<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Quantizer<'a> {
    type Inner = Quantizer<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> Quantizer<'a> {
    pub const VT_TRANSFORM: flatbuffers::VOffsetT = 4;
    pub const VT_GRID_SCALE: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Quantizer { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args QuantizerArgs<'args>,
    ) -> flatbuffers::WIPOffset<Quantizer<'bldr>> {
        let mut builder = QuantizerBuilder::new(_fbb);
        builder.add_grid_scale(args.grid_scale);
        if let Some(x) = args.transform {
            builder.add_transform(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn transform(&self) -> super::transforms::Transform<'a> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<super::transforms::Transform>>(
                    Quantizer::VT_TRANSFORM,
                    None,
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn grid_scale(&self) -> f32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<f32>(Quantizer::VT_GRID_SCALE, Some(0.0))
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for Quantizer<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<super::transforms::Transform>>(
                "transform",
                Self::VT_TRANSFORM,
                true,
            )?
            .visit_field::<f32>("grid_scale", Self::VT_GRID_SCALE, false)?
            .finish();
        Ok(())
    }
}
pub struct QuantizerArgs<'a> {
    pub transform: Option<flatbuffers::WIPOffset<super::transforms::Transform<'a>>>,
    pub grid_scale: f32,
}
impl<'a> Default for QuantizerArgs<'a> {
    #[inline]
    fn default() -> Self {
        QuantizerArgs {
            transform: None, // required field
            grid_scale: 0.0,
        }
    }
}

pub struct QuantizerBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> QuantizerBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_transform(
        &mut self,
        transform: flatbuffers::WIPOffset<super::transforms::Transform<'b>>,
    ) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<super::transforms::Transform>>(
                Quantizer::VT_TRANSFORM,
                transform,
            );
    }
    #[inline]
    pub fn add_grid_scale(&mut self, grid_scale: f32) {
        self.fbb_
            .push_slot::<f32>(Quantizer::VT_GRID_SCALE, grid_scale, 0.0);
    }
    #[inline]
    pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> QuantizerBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        QuantizerBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<Quantizer<'a>> {
        let o = self.fbb_.end_table(self.start_);
        self.fbb_.required(o, Quantizer::VT_TRANSFORM, "transform");
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for Quantizer<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("Quantizer");
        ds.field("transform", &self.transform());
        ds.field("grid_scale", &self.grid_scale());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Quantizer`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_quantizer_unchecked`.
pub fn root_as_quantizer(buf: &[u8]) -> Result<Quantizer, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<Quantizer>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Quantizer` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_quantizer_unchecked`.
pub fn size_prefixed_root_as_quantizer(
    buf: &[u8],
) -> Result<Quantizer, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<Quantizer>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Quantizer` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_quantizer_unchecked`.
pub fn root_as_quantizer_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<Quantizer<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<Quantizer<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Quantizer` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_quantizer_unchecked`.
pub fn size_prefixed_root_as_quantizer_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<Quantizer<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<Quantizer<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Quantizer and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Quantizer`.
pub unsafe fn root_as_quantizer_unchecked(buf: &[u8]) -> Quantizer {
    flatbuffers::root_unchecked::<Quantizer>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Quantizer and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Quantizer`.
pub unsafe fn size_prefixed_root_as_quantizer_unchecked(buf: &[u8]) -> Quantizer {
    flatbuffers::size_prefixed_root_unchecked::<Quantizer>(buf)
}
pub const QUANTIZER_IDENTIFIER: &str = "mq00";

#[inline]
pub fn quantizer_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, QUANTIZER_IDENTIFIER, false)
}

#[inline]
pub fn quantizer_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, QUANTIZER_IDENTIFIER, true)
}

#[inline]
pub fn finish_quantizer_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Quantizer<'a>>,
) {
    fbb.finish(root, Some(QUANTIZER_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_quantizer_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Quantizer<'a>>,
) {
    fbb.finish_size_prefixed(root, Some(QUANTIZER_IDENTIFIER));
}
