/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

use std::{error::Error, fmt};

/// Error that wraps all errors generated by command-line tools
#[derive(PartialEq)]
pub struct CMDToolError {
    pub details: String,
}

impl fmt::Display for CMDToolError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.details)
    }
}

// Implement `Debug` in terms of `Display` so when `CMDToolError` hits the top level, we
// get proper formatting.
impl fmt::Debug for CMDToolError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        <Self as fmt::Display>::fmt(self, f)
    }
}

impl Error for CMDToolError {
    fn description(&self) -> &str {
        &self.details
    }
}

impl From<std::io::Error> for CMDToolError {
    fn from(err: std::io::Error) -> Self {
        CMDToolError {
            details: err.to_string(),
        }
    }
}

impl From<rand_distr::NormalError> for CMDToolError {
    fn from(err: rand_distr::NormalError) -> Self {
        CMDToolError {
            details: err.to_string(),
        }
    }
}
impl From<diskann::ANNError> for CMDToolError {
    fn from(err: diskann::ANNError) -> Self {
        CMDToolError {
            details: err.to_string(),
        }
    }
}
impl From<diskann::graph::config::ConfigError> for CMDToolError {
    fn from(err: diskann::graph::config::ConfigError) -> Self {
        CMDToolError {
            details: err.to_string(),
        }
    }
}

impl From<diskann_label_filter::JsonlReadError> for CMDToolError {
    fn from(err: diskann_label_filter::JsonlReadError) -> Self {
        CMDToolError {
            details: err.to_string(),
        }
    }
}

impl<T, U> From<diskann_providers::utils::MetadataError<T, U>> for CMDToolError
where
    T: std::error::Error + Send + Sync + 'static,
    U: std::error::Error + Send + Sync + 'static,
{
    fn from(err: diskann_providers::utils::MetadataError<T, U>) -> Self {
        // Leverage the existing conversion chain: MetadataError -> ANNError -> CMDToolError
        let ann_error: diskann::ANNError = err.into();
        ann_error.into()
    }
}
