# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.

# Codecov configuration for DiskANN Rust code coverage
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    # Project coverage (overall) - informational only
    project:
      default:
        target: auto
        threshold: 1%
        informational: true

    # Patch coverage (changed lines only) - this will block PRs
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: false

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: miri
      carryforward: true
      statuses:
        - type: project
          target: 0%
        - type: patch
          target: 0%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "test_data/**"
  - "**/*_test.rs"
  - "**/tests/**"
  - "**/benches/**"
  - "**/examples/**"
