allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true

disallowed-methods = [
    { path = "bf_tree::BfTree::insert", reason = "This method is fallible but returns a `bool`. Use `crate::bftree_insert` instead" }
]
