# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
[package]
name = "vector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.2.1"
thiserror = "1.0.40"
bytemuck = "1.7.0"

[build-dependencies]
cc = "1.0.79"

[dev-dependencies]
base64 = "0.21.2"
bincode = "1.3.3"
serde = "1.0.163"
approx = "0.5.1"
rand = "0.8.5"

