[package]
name = "vectorset"
version = "1.0.0"
edition = "2024"
authors = ["Microsoft"]
license = "MIT"
repository = "https://github.com/microsoft/DiskANN"
publish = false

[dependencies]
anyhow = "1.0.98"
azure_core = "1.1"
azure_identity = "1.0"
bytemuck = "1.23.0"
clap = { version = "4.5.45", features = ["derive"] }
chrono = { version = "0.4.45", features = ["serde"] }
diskann-benchmark-core = "0.55.0"
diskann-benchmark-runner = "0.55.0"
diskann-utils = "0.55.0"
indicatif = "0.18.3"
rand = "0.10.2"
redis = { version = "1.4.1", features = [
    "tokio-native-tls-comp",
    "vector-sets",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde-saphyr = "1.0.0-rc.1"
serde_json = "1.0.151"
thiserror = "2.0.19"
tokio = { version = "1.48.0", features = [
    "rt-multi-thread",
    "net",
    "macros",
    "fs",
    "sync",
] }
toml = "1.1.3"

[dev-dependencies]
tempfile = "3.27.0"
