# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
[package]
name = "build_disk_index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diskann = { path = "../../diskann" }
logger = { path = "../../logger" }
vector = { path = "../../vector" }
openblas-src = { version = "0.10.8", features = ["system", "static"] }
