# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
[package]
name = "diskann"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3" 
bit-vec = "0.6.3"
byteorder = "1.4.3"
cblas = "0.4.0"
crossbeam = "0.8.2"
half = "2.2.1"
hashbrown = "0.13.2"
num-traits = "0.2.15"
once_cell = "1.17.1"
openblas-src = { version = "0.10.8", features = ["system"] }
rand = { version = "0.8.5", features = [ "small_rng" ] }
rayon = "1.7.0"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.40"
winapi = { version = "0.3.9", features = ["errhandlingapi", "fileapi", "ioapiset", "handleapi", "winnt", "minwindef", "basetsd", "winerror", "winbase"] }

logger = { path = "../logger" }
platform = { path = "../platform" }
vector = { path = "../vector" }

[build-dependencies]
cc = "1.0.79"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"


[[bench]]
name = "distance_bench"
harness = false

[[bench]]
name = "neighbor_bench"
harness = false
