/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

#[cfg(not(target_endian = "little"))]
compile_error!("diskann-utils assumes little-endian targets");

pub mod reborrow;
pub use reborrow::{Reborrow, ReborrowMut};

pub mod lifetime;
pub use lifetime::WithLifetime;

pub mod future;

pub mod io;
pub mod object_pool;
pub mod sampling;
pub mod streaming;

// Views
pub mod strided;
pub mod views;

mod lazystring;
pub use lazystring::LazyString;

#[cfg(feature = "testing")]
#[doc(hidden)]
pub fn workspace_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

#[cfg(feature = "testing")]
#[doc(hidden)]
pub fn test_data_directory() -> &'static str {
    "test_data"
}

#[cfg(feature = "testing")]
#[doc(hidden)]
pub fn test_data_root() -> std::path::PathBuf {
    workspace_root().join(test_data_directory())
}

/// # Notes on Testing
///
/// BigANN parsing UX tests use checked-in fixtures under the crate's `tests` directory.
/// Expected outputs can be regenerated by running tests with `DISKANN_TEST=overwrite`.
#[cfg(all(test, feature = "bigann"))]
mod ux {
    const ENV_VAR: &str = "DISKANN_TEST";

    /// Check if we should overwrite expected files.
    pub(crate) fn should_overwrite() -> bool {
        match std::env::var(ENV_VAR) {
            Ok(v) if v == "overwrite" => true,
            Ok(v) => panic!(
                "Unknown value for {}: \"{}\". Expected \"overwrite\"",
                ENV_VAR, v
            ),
            Err(std::env::VarError::NotPresent) => false,
            Err(std::env::VarError::NotUnicode(_)) => {
                panic!("Value for {} is not unicode", ENV_VAR)
            }
        }
    }

    pub(crate) fn help() -> String {
        format!("{}=overwrite", ENV_VAR)
    }

    pub(crate) fn test_dir() -> std::path::PathBuf {
        let manifest: &std::path::Path = env!("CARGO_MANIFEST_DIR").as_ref();
        manifest.join("tests")
    }
}
