/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum DoubleHadamardOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DoubleHadamard<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DoubleHadamard<'a> {
  type Inner = DoubleHadamard<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DoubleHadamard<'a> {
  pub const VT_SIGNS0: flatbuffers::VOffsetT = 4;
  pub const VT_SIGNS1: flatbuffers::VOffsetT = 6;
  pub const VT_SUBSAMPLE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DoubleHadamard { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DoubleHadamardArgs<'args>
  ) -> flatbuffers::WIPOffset<DoubleHadamard<'bldr>> {
    let mut builder = DoubleHadamardBuilder::new(_fbb);
    if let Some(x) = args.subsample { builder.add_subsample(x); }
    if let Some(x) = args.signs1 { builder.add_signs1(x); }
    if let Some(x) = args.signs0 { builder.add_signs0(x); }
    builder.finish()
  }


  #[inline]
  pub fn signs0(&self) -> flatbuffers::Vector<'a, bool> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(DoubleHadamard::VT_SIGNS0, None).unwrap()}
  }
  #[inline]
  pub fn signs1(&self) -> flatbuffers::Vector<'a, bool> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(DoubleHadamard::VT_SIGNS1, None).unwrap()}
  }
  #[inline]
  pub fn subsample(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(DoubleHadamard::VT_SUBSAMPLE, None)}
  }
}

impl flatbuffers::Verifiable for DoubleHadamard<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, bool>>>("signs0", Self::VT_SIGNS0, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, bool>>>("signs1", Self::VT_SIGNS1, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("subsample", Self::VT_SUBSAMPLE, false)?
     .finish();
    Ok(())
  }
}
pub struct DoubleHadamardArgs<'a> {
    pub signs0: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
    pub signs1: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
    pub subsample: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for DoubleHadamardArgs<'a> {
  #[inline]
  fn default() -> Self {
    DoubleHadamardArgs {
      signs0: None, // required field
      signs1: None, // required field
      subsample: None,
    }
  }
}

pub struct DoubleHadamardBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DoubleHadamardBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_signs0(&mut self, signs0: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DoubleHadamard::VT_SIGNS0, signs0);
  }
  #[inline]
  pub fn add_signs1(&mut self, signs1: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DoubleHadamard::VT_SIGNS1, signs1);
  }
  #[inline]
  pub fn add_subsample(&mut self, subsample: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DoubleHadamard::VT_SUBSAMPLE, subsample);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DoubleHadamardBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DoubleHadamardBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DoubleHadamard<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DoubleHadamard::VT_SIGNS0,"signs0");
    self.fbb_.required(o, DoubleHadamard::VT_SIGNS1,"signs1");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DoubleHadamard<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DoubleHadamard");
      ds.field("signs0", &self.signs0());
      ds.field("signs1", &self.signs1());
      ds.field("subsample", &self.subsample());
      ds.finish()
  }
}
