/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum NullTransformOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NullTransform<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NullTransform<'a> {
  type Inner = NullTransform<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NullTransform<'a> {
  pub const VT_DIM: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NullTransform { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NullTransformArgs
  ) -> flatbuffers::WIPOffset<NullTransform<'bldr>> {
    let mut builder = NullTransformBuilder::new(_fbb);
    builder.add_dim(args.dim);
    builder.finish()
  }


  #[inline]
  pub fn dim(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NullTransform::VT_DIM, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for NullTransform<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("dim", Self::VT_DIM, false)?
     .finish();
    Ok(())
  }
}
pub struct NullTransformArgs {
    pub dim: u32,
}
impl<'a> Default for NullTransformArgs {
  #[inline]
  fn default() -> Self {
    NullTransformArgs {
      dim: 0,
    }
  }
}

pub struct NullTransformBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NullTransformBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_dim(&mut self, dim: u32) {
    self.fbb_.push_slot::<u32>(NullTransform::VT_DIM, dim, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NullTransformBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NullTransformBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NullTransform<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NullTransform<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NullTransform");
      ds.field("dim", &self.dim());
      ds.finish()
  }
}
