// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PaddingHadamardOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PaddingHadamard<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PaddingHadamard<'a> {
  type Inner = PaddingHadamard<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> PaddingHadamard<'a> {
  pub const VT_SIGNS: flatbuffers::VOffsetT = 4;
  pub const VT_PADDED_DIM: flatbuffers::VOffsetT = 6;
  pub const VT_SUBSAMPLE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PaddingHadamard { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args PaddingHadamardArgs<'args>
  ) -> flatbuffers::WIPOffset<PaddingHadamard<'bldr>> {
    let mut builder = PaddingHadamardBuilder::new(_fbb);
    if let Some(x) = args.subsample { builder.add_subsample(x); }
    builder.add_padded_dim(args.padded_dim);
    if let Some(x) = args.signs { builder.add_signs(x); }
    builder.finish()
  }


  #[inline]
  pub fn signs(&self) -> &'a [bool] {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(PaddingHadamard::VT_SIGNS, None).map(|v| v.safe_slice()).unwrap()
  }
  #[inline]
  pub fn padded_dim(&self) -> u32 {
    self._tab.get::<u32>(PaddingHadamard::VT_PADDED_DIM, Some(0)).unwrap()
  }
  #[inline]
  pub fn subsample(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(PaddingHadamard::VT_SUBSAMPLE, None)
  }
}

impl flatbuffers::Verifiable for PaddingHadamard<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, bool>>>("signs", Self::VT_SIGNS, true)?
     .visit_field::<u32>("padded_dim", Self::VT_PADDED_DIM, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("subsample", Self::VT_SUBSAMPLE, false)?
     .finish();
    Ok(())
  }
}
pub struct PaddingHadamardArgs<'a> {
    pub signs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
    pub padded_dim: u32,
    pub subsample: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for PaddingHadamardArgs<'a> {
  #[inline]
  fn default() -> Self {
    PaddingHadamardArgs {
      signs: None, // required field
      padded_dim: 0,
      subsample: None,
    }
  }
}

pub struct PaddingHadamardBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> PaddingHadamardBuilder<'a, 'b> {
  #[inline]
  pub fn add_signs(&mut self, signs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PaddingHadamard::VT_SIGNS, signs);
  }
  #[inline]
  pub fn add_padded_dim(&mut self, padded_dim: u32) {
    self.fbb_.push_slot::<u32>(PaddingHadamard::VT_PADDED_DIM, padded_dim, 0);
  }
  #[inline]
  pub fn add_subsample(&mut self, subsample: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PaddingHadamard::VT_SUBSAMPLE, subsample);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> PaddingHadamardBuilder<'a, 'b> {
    let start = _fbb.start_table();
    PaddingHadamardBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PaddingHadamard<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PaddingHadamard::VT_SIGNS,"signs");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PaddingHadamard<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PaddingHadamard");
      ds.field("signs", &self.signs());
      ds.field("padded_dim", &self.padded_dim());
      ds.field("subsample", &self.subsample());
      ds.finish()
  }
}
