/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TransformOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Transform<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Transform<'a> {
  type Inner = Transform<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Transform<'a> {
  pub const VT_TRANSFORM_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_TRANSFORM: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Transform { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TransformArgs
  ) -> flatbuffers::WIPOffset<Transform<'bldr>> {
    let mut builder = TransformBuilder::new(_fbb);
    if let Some(x) = args.transform { builder.add_transform(x); }
    builder.add_transform_type(args.transform_type);
    builder.finish()
  }


  #[inline]
  pub fn transform_type(&self) -> TransformKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TransformKind>(Transform::VT_TRANSFORM_TYPE, Some(TransformKind::NONE)).unwrap()}
  }
  #[inline]
  pub fn transform(&self) -> flatbuffers::Table<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Transform::VT_TRANSFORM, None).unwrap()}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn transform_as_random_rotation(&self) -> Option<RandomRotation<'a>> {
    if self.transform_type() == TransformKind::RandomRotation {
      let u = self.transform();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { RandomRotation::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn transform_as_padding_hadamard(&self) -> Option<PaddingHadamard<'a>> {
    if self.transform_type() == TransformKind::PaddingHadamard {
      let u = self.transform();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { PaddingHadamard::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn transform_as_double_hadamard(&self) -> Option<DoubleHadamard<'a>> {
    if self.transform_type() == TransformKind::DoubleHadamard {
      let u = self.transform();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { DoubleHadamard::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn transform_as_null_transform(&self) -> Option<NullTransform<'a>> {
    if self.transform_type() == TransformKind::NullTransform {
      let u = self.transform();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { NullTransform::init_from_table(u) })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for Transform<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<TransformKind, _>("transform_type", Self::VT_TRANSFORM_TYPE, "transform", Self::VT_TRANSFORM, true, |key, v, pos| {
        match key {
          TransformKind::RandomRotation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<RandomRotation>>("TransformKind::RandomRotation", pos),
          TransformKind::PaddingHadamard => v.verify_union_variant::<flatbuffers::ForwardsUOffset<PaddingHadamard>>("TransformKind::PaddingHadamard", pos),
          TransformKind::DoubleHadamard => v.verify_union_variant::<flatbuffers::ForwardsUOffset<DoubleHadamard>>("TransformKind::DoubleHadamard", pos),
          TransformKind::NullTransform => v.verify_union_variant::<flatbuffers::ForwardsUOffset<NullTransform>>("TransformKind::NullTransform", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct TransformArgs {
    pub transform_type: TransformKind,
    pub transform: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for TransformArgs {
  #[inline]
  fn default() -> Self {
    TransformArgs {
      transform_type: TransformKind::NONE,
      transform: None, // required field
    }
  }
}

pub struct TransformBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TransformBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_transform_type(&mut self, transform_type: TransformKind) {
    self.fbb_.push_slot::<TransformKind>(Transform::VT_TRANSFORM_TYPE, transform_type, TransformKind::NONE);
  }
  #[inline]
  pub fn add_transform(&mut self, transform: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Transform::VT_TRANSFORM, transform);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TransformBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TransformBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Transform<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Transform::VT_TRANSFORM,"transform");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Transform<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Transform");
      ds.field("transform_type", &self.transform_type());
      match self.transform_type() {
        TransformKind::RandomRotation => {
          if let Some(x) = self.transform_as_random_rotation() {
            ds.field("transform", &x)
          } else {
            ds.field("transform", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        TransformKind::PaddingHadamard => {
          if let Some(x) = self.transform_as_padding_hadamard() {
            ds.field("transform", &x)
          } else {
            ds.field("transform", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        TransformKind::DoubleHadamard => {
          if let Some(x) = self.transform_as_double_hadamard() {
            ds.field("transform", &x)
          } else {
            ds.field("transform", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        TransformKind::NullTransform => {
          if let Some(x) = self.transform_as_null_transform() {
            ds.field("transform", &x)
          } else {
            ds.field("transform", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("transform", &x)
        },
      };
      ds.finish()
  }
}
