#include <algorithm>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <fcntl.h>
#include <fstream>
#include <iostream>
#include <queue>
#include <random>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <vector>
