/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum SphericalQuantizerOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SphericalQuantizer<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SphericalQuantizer<'a> {
  type Inner = SphericalQuantizer<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SphericalQuantizer<'a> {
  pub const VT_CENTROID: flatbuffers::VOffsetT = 4;
  pub const VT_TRANSFORM: flatbuffers::VOffsetT = 6;
  pub const VT_METRIC: flatbuffers::VOffsetT = 8;
  pub const VT_MEAN_NORM: flatbuffers::VOffsetT = 10;
  pub const VT_PRE_SCALE: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SphericalQuantizer { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SphericalQuantizerArgs<'args>
  ) -> flatbuffers::WIPOffset<SphericalQuantizer<'bldr>> {
    let mut builder = SphericalQuantizerBuilder::new(_fbb);
    builder.add_pre_scale(args.pre_scale);
    builder.add_mean_norm(args.mean_norm);
    if let Some(x) = args.transform { builder.add_transform(x); }
    if let Some(x) = args.centroid { builder.add_centroid(x); }
    builder.add_metric(args.metric);
    builder.finish()
  }


  #[inline]
  pub fn centroid(&self) -> flatbuffers::Vector<'a, f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(SphericalQuantizer::VT_CENTROID, None).unwrap()}
  }
  #[inline]
  pub fn transform(&self) -> super::transforms::Transform<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::transforms::Transform>>(SphericalQuantizer::VT_TRANSFORM, None).unwrap()}
  }
  #[inline]
  pub fn metric(&self) -> SupportedMetric {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<SupportedMetric>(SphericalQuantizer::VT_METRIC, Some(SupportedMetric::SquaredL2)).unwrap()}
  }
  #[inline]
  pub fn mean_norm(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SphericalQuantizer::VT_MEAN_NORM, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn pre_scale(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SphericalQuantizer::VT_PRE_SCALE, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for SphericalQuantizer<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f32>>>("centroid", Self::VT_CENTROID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::transforms::Transform>>("transform", Self::VT_TRANSFORM, true)?
     .visit_field::<SupportedMetric>("metric", Self::VT_METRIC, false)?
     .visit_field::<f32>("mean_norm", Self::VT_MEAN_NORM, false)?
     .visit_field::<f32>("pre_scale", Self::VT_PRE_SCALE, false)?
     .finish();
    Ok(())
  }
}
pub struct SphericalQuantizerArgs<'a> {
    pub centroid: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
    pub transform: Option<flatbuffers::WIPOffset<super::transforms::Transform<'a>>>,
    pub metric: SupportedMetric,
    pub mean_norm: f32,
    pub pre_scale: f32,
}
impl<'a> Default for SphericalQuantizerArgs<'a> {
  #[inline]
  fn default() -> Self {
    SphericalQuantizerArgs {
      centroid: None, // required field
      transform: None, // required field
      metric: SupportedMetric::SquaredL2,
      mean_norm: 0.0,
      pre_scale: 0.0,
    }
  }
}

pub struct SphericalQuantizerBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SphericalQuantizerBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_centroid(&mut self, centroid: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SphericalQuantizer::VT_CENTROID, centroid);
  }
  #[inline]
  pub fn add_transform(&mut self, transform: flatbuffers::WIPOffset<super::transforms::Transform<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::transforms::Transform>>(SphericalQuantizer::VT_TRANSFORM, transform);
  }
  #[inline]
  pub fn add_metric(&mut self, metric: SupportedMetric) {
    self.fbb_.push_slot::<SupportedMetric>(SphericalQuantizer::VT_METRIC, metric, SupportedMetric::SquaredL2);
  }
  #[inline]
  pub fn add_mean_norm(&mut self, mean_norm: f32) {
    self.fbb_.push_slot::<f32>(SphericalQuantizer::VT_MEAN_NORM, mean_norm, 0.0);
  }
  #[inline]
  pub fn add_pre_scale(&mut self, pre_scale: f32) {
    self.fbb_.push_slot::<f32>(SphericalQuantizer::VT_PRE_SCALE, pre_scale, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SphericalQuantizerBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SphericalQuantizerBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SphericalQuantizer<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, SphericalQuantizer::VT_CENTROID,"centroid");
    self.fbb_.required(o, SphericalQuantizer::VT_TRANSFORM,"transform");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SphericalQuantizer<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SphericalQuantizer");
      ds.field("centroid", &self.centroid());
      ds.field("transform", &self.transform());
      ds.field("metric", &self.metric());
      ds.field("mean_norm", &self.mean_norm());
      ds.field("pre_scale", &self.pre_scale());
      ds.finish()
  }
}
