name: DiskANN Build Python Wheel
on: [workflow_call]
jobs:
  build:
    name: Build for ${{matrix.python-version}} on ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.3
      - name: Building Wheel for Python ${{inputs.python-version}}
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ inputs.python-version }}
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.whl
