name: DiskANN Build Python Wheel
on: [workflow_call]
jobs:
  linux-build:
    name: Python - Ubuntu - ${{matrix.cibw-identifier}}
    strategy:
      fail-fast: false
      matrix:
        cibw-identifier: ["cp39-manylinux_x86_64", "cp310-manylinux_x86_64", "cp311-manylinux_x86_64"]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Building python wheel ${{matrix.cibw-identifier}}
        uses: ./.github/actions/python-wheel
        with:
          cibw-identifier: ${{matrix.cibw-identifier}}
      - name: Build dependency tree
        run: |
          pip install pipdeptree
          echo "documentation" > dependencies_documentation.txt
          pipdeptree >> dependencies_${{matrix.cibw-identifier}.txt
      - name: Archive dependencies artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: |
            dependencies_${{matrix.cibw-identifier}.txt
  windows-build:
    name: Python - Windows - ${{matrix.cibw-identifier}}
    strategy:
      fail-fast: false
      matrix:
        cibw-identifier: ["cp39-win_amd64", "cp310-win_amd64", "cp311-win_amd64"]
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: Building python wheel ${{matrix.cibw-identifier}}
        uses: ./.github/actions/python-wheel
        with:
          cibw-identifier: ${{matrix.cibw-identifier}}
      - name: Build dependency tree
        run: |
          pip install pipdeptree
          echo "documentation" > dependencies_documentation.txt
          pipdeptree >> dependencies_${{matrix.cibw-identifier}.txt
      - name: Archive dependencies artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: |
            dependencies_${{matrix.cibw-identifier}.txt
