name: DiskANN Build and run
on: [pull_request]
jobs:
  ubuntu-latest-build-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install cmake g++ libaio-dev libgoogle-perftools-dev clang-format libboost-dev libboost-program-options-dev libmkl-full-dev
    - name: build
      run: |
        mkdir build && cd build && cmake .. && make -j

    - name: Generate 10K random floating points in 10 dims and compute GT
      run: |
        ./build/tests/utils/rand_data_gen --data_type float --output_file ./rand_float_10D_10K_norm1.0.bin -D 10 -N 10000 --norm 1.0
        ./build/tests/utils/compute_groundtruth  --data_type float --dist_fn l2 --base_file ./rand_float_10D_10K_norm1.0.bin --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./l2_rand_float_10D_10K_norm1.0_self_gt100 --K 100
        ./build/tests/utils/compute_groundtruth  --data_type float --dist_fn mips --base_file ./rand_float_10D_10K_norm1.0.bin --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./mips_rand_float_10D_10K_norm1.0_self_gt100 --K 100
        ./build/tests/utils/compute_groundtruth  --data_type float --dist_fn cosine --base_file ./rand_float_10D_10K_norm1.0.bin --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./cosine_rand_float_10D_10K_norm1.0_self_gt100 --K 100
    - name: build and search in-memory index with L2 metrics
      run: |   
        ./build/tests/build_memory_index --data_type float --dist_fn l2 --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./index_l2_rand_float_10D_10K_norm1.0
        ./build/tests/search_memory_index --data_type float --dist_fn l2 --index_path_prefix ./index_l2_rand_float_10D_10K_norm1.0 --query_file ./rand_float_10D_10K_norm1.0.bin --recall_at 10 --result_path temp --gt_file ./l2_rand_float_10D_10K_norm1.0_self_gt100 -L  16 32
        ./build/tests/search_memory_index --data_type float --dist_fn fast_l2 --index_path_prefix ./index_l2_rand_float_10D_10K_norm1.0 --query_file ./rand_float_10D_10K_norm1.0.bin --recall_at 10 --result_path temp --gt_file ./l2_rand_float_10D_10K_norm1.0_self_gt100 -L  16 32
    - name: build and search in-memory index with MIPS metric
      run: |   
        ./build/tests/build_memory_index --data_type float --dist_fn mips --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./index_mips_rand_float_10D_10K_norm1.0
        ./build/tests/search_memory_index --data_type float --dist_fn mips --index_path_prefix ./index_l2_rand_float_10D_10K_norm1.0 --query_file ./rand_float_10D_10K_norm1.0.bin --recall_at 10 --result_path temp --gt_file ./mips_rand_float_10D_10K_norm1.0_self_gt100 -L  16 32
    - name: build and search in-memory index with cosine metric
      run: |   
        ./build/tests/build_memory_index --data_type float --dist_fn cosine --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./index_cosine_rand_float_10D_10K_norm1.0
        ./build/tests/search_memory_index --data_type float --dist_fn cosine --index_path_prefix ./index_l2_rand_float_10D_10K_norm1.0 --query_file ./rand_float_10D_10K_norm1.0.bin --recall_at 10 --result_path temp --gt_file ./cosine_rand_float_10D_10K_norm1.0_self_gt100 -L  16 32
    - name: build and search disk index (one shot graph build, L2, no diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type float --dist_fn l2 --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./disk_index_l2_rand_float_10D_10K_norm1.0_diskfull_oneshot -R 16 -L 32 -B 0.00003 -M 1 
        ./build/tests/search_disk_index --data_type float --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_float_10D_10K_norm1.0_diskfull_oneshot --result_path /tmp/res --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./l2_rand_float_10D_10K_norm1.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (sharded graph build, L2, no diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type float --dist_fn l2 --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./disk_index_l2_rand_float_10D_10K_norm1.0_diskfull_sharded -R 16 -L 32 -B 0.00003 -M 0.00006
        ./build/tests/search_disk_index --data_type float --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_float_10D_10K_norm1.0_diskfull_sharded --result_path /tmp/res --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./l2_rand_float_10D_10K_norm1.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (one shot graph build, L2, diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type float --dist_fn l2 --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./disk_index_l2_rand_float_10D_10K_norm1.0_diskpq_oneshot -R 16 -L 32 -B 0.00003 -M 1 --PQ_disk_bytes 5
        ./build/tests/search_disk_index --data_type float --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_float_10D_10K_norm1.0_diskpq_oneshot --result_path /tmp/res --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./l2_rand_float_10D_10K_norm1.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (sharded graph build, MIPS, diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type float --dist_fn mips --data_path ./rand_float_10D_10K_norm1.0.bin --index_path_prefix ./disk_index_mips_rand_float_10D_10K_norm1.0_diskpq_sharded -R 16 -L 32 -B 0.00003 -M 0.00006 --PQ_disk_bytes 5
        ./build/tests/search_disk_index --data_type float --dist_fn l2 --index_path_prefix ./disk_index_mips_rand_float_10D_10K_norm1.0_diskpq_sharded --result_path /tmp/res --query_file ./rand_float_10D_10K_norm1.0.bin --gt_file ./mips_rand_float_10D_10K_norm1.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    


    - name: Generate 10K random int8 points in 10 dims and compute GT
      run: |
        ./build/tests/utils/rand_data_gen --data_type int8 --output_file ./rand_int8_10D_10K_norm50.0.bin -D 10 -N 10000 --norm 50.0
        ./build/tests/utils/compute_groundtruth  --data_type int8 --dist_fn l2 --base_file ./rand_int8_10D_10K_norm50.0.bin --query_file ./rand_int8_10D_10K_norm50.0.bin --gt_file ./l2_rand_int8_10D_10K_norm50.0_self_gt100 --K 100
        ./build/tests/utils/compute_groundtruth  --data_type int8 --dist_fn mips --base_file ./rand_int8_10D_10K_norm50.0.bin --query_file ./rand_int8_10D_10K_norm50.0.bin --gt_file ./mips_rand_int8_10D_10K_norm50.0_self_gt100 --K 100
        ./build/tests/utils/compute_groundtruth  --data_type int8 --dist_fn cosine --base_file ./rand_int8_10D_10K_norm50.0.bin --query_file ./rand_int8_10D_10K_norm50.0.bin --gt_file ./cosine_rand_int8_10D_10K_norm50.0_self_gt100 --K 100
    - name: build and search in-memory index with L2 metrics
      run: |   
        ./build/tests/build_memory_index --data_type int8 --dist_fn l2 --data_path ./rand_int8_10D_10K_norm50.0.bin --index_path_prefix ./index_l2_rand_int8_10D_10K_norm50.0
        ./build/tests/search_memory_index --data_type int8 --dist_fn l2 --index_path_prefix ./index_l2_rand_int8_10D_10K_norm50.0 --query_file ./rand_int8_10D_10K_norm50.0.bin --recall_at 10 --result_path temp --gt_file ./l2_rand_int8_10D_10K_norm50.0_self_gt100 -L  16 32
    - name: build and search in-memory index with cosine metric
      run: |   
        ./build/tests/build_memory_index --data_type int8 --dist_fn cosine --data_path ./rand_int8_10D_10K_norm50.0.bin --index_path_prefix ./index_cosine_rand_int8_10D_10K_norm50.0
        ./build/tests/search_memory_index --data_type int8 --dist_fn cosine --index_path_prefix ./index_l2_rand_int8_10D_10K_norm50.0 --query_file ./rand_int8_10D_10K_norm50.0.bin --recall_at 10 --result_path temp --gt_file ./cosine_rand_int8_10D_10K_norm50.0_self_gt100 -L  16 32
    - name: build and search disk index (one shot graph build, L2, no diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type int8 --dist_fn l2 --data_path ./rand_int8_10D_10K_norm50.0.bin --index_path_prefix ./disk_index_l2_rand_int8_10D_10K_norm50.0_diskfull_oneshot -R 16 -L 32 -B 0.00003 -M 1 
        ./build/tests/search_disk_index --data_type int8 --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_int8_10D_10K_norm50.0_diskfull_oneshot --result_path /tmp/res --query_file ./rand_int8_10D_10K_norm50.0.bin --gt_file ./l2_rand_int8_10D_10K_norm50.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (sharded graph build, L2, no diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type int8 --dist_fn l2 --data_path ./rand_int8_10D_10K_norm50.0.bin --index_path_prefix ./disk_index_l2_rand_int8_10D_10K_norm50.0_diskfull_sharded -R 16 -L 32 -B 0.00003 -M 0.00006
        ./build/tests/search_disk_index --data_type int8 --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_int8_10D_10K_norm50.0_diskfull_sharded --result_path /tmp/res --query_file ./rand_int8_10D_10K_norm50.0.bin --gt_file ./l2_rand_int8_10D_10K_norm50.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (one shot graph build, L2, diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type int8 --dist_fn l2 --data_path ./rand_int8_10D_10K_norm50.0.bin --index_path_prefix ./disk_index_l2_rand_int8_10D_10K_norm50.0_diskpq_oneshot -R 16 -L 32 -B 0.00003 -M 1 --PQ_disk_bytes 5
        ./build/tests/search_disk_index --data_type int8 --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_int8_10D_10K_norm50.0_diskpq_oneshot --result_path /tmp/res --query_file ./rand_int8_10D_10K_norm50.0.bin --gt_file ./l2_rand_int8_10D_10K_norm50.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16



    - name: Generate 10K random uint8 points in 10 dims and compute GT
      run: |
        ./build/tests/utils/rand_data_gen --data_type uint8 --output_file ./rand_uint8_10D_10K_norm50.0.bin -D 10 -N 10000 --norm 50.0
        ./build/tests/utils/compute_groundtruth  --data_type uint8 --dist_fn l2 --base_file ./rand_uint8_10D_10K_norm50.0.bin --query_file ./rand_uint8_10D_10K_norm50.0.bin --gt_file ./l2_rand_uint8_10D_10K_norm50.0_self_gt100 --K 100
        ./build/tests/utils/compute_groundtruth  --data_type uint8 --dist_fn mips --base_file ./rand_uint8_10D_10K_norm50.0.bin --query_file ./rand_uint8_10D_10K_norm50.0.bin --gt_file ./mips_rand_uint8_10D_10K_norm50.0_self_gt100 --K 100
        ./build/tests/utils/compute_groundtruth  --data_type uint8 --dist_fn cosine --base_file ./rand_uint8_10D_10K_norm50.0.bin --query_file ./rand_uint8_10D_10K_norm50.0.bin --gt_file ./cosine_rand_uint8_10D_10K_norm50.0_self_gt100 --K 100
    - name: build and search in-memory index with L2 metrics
      run: |   
        ./build/tests/build_memory_index --data_type uint8 --dist_fn l2 --data_path ./rand_uint8_10D_10K_norm50.0.bin --index_path_prefix ./index_l2_rand_uint8_10D_10K_norm50.0
        ./build/tests/search_memory_index --data_type uint8 --dist_fn l2 --index_path_prefix ./index_l2_rand_uint8_10D_10K_norm50.0 --query_file ./rand_uint8_10D_10K_norm50.0.bin --recall_at 10 --result_path temp --gt_file ./l2_rand_uint8_10D_10K_norm50.0_self_gt100 -L  16 32
    - name: build and search in-memory index with cosine metric
      run: |   
        ./build/tests/build_memory_index --data_type uint8 --dist_fn cosine --data_path ./rand_uint8_10D_10K_norm50.0.bin --index_path_prefix ./index_cosine_rand_uint8_10D_10K_norm50.0
        ./build/tests/search_memory_index --data_type uint8 --dist_fn cosine --index_path_prefix ./index_l2_rand_uint8_10D_10K_norm50.0 --query_file ./rand_uint8_10D_10K_norm50.0.bin --recall_at 10 --result_path temp --gt_file ./cosine_rand_uint8_10D_10K_norm50.0_self_gt100 -L  16 32
    - name: build and search disk index (one shot graph build, L2, no diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type uint8 --dist_fn l2 --data_path ./rand_uint8_10D_10K_norm50.0.bin --index_path_prefix ./disk_index_l2_rand_uint8_10D_10K_norm50.0_diskfull_oneshot -R 16 -L 32 -B 0.00003 -M 1 
        ./build/tests/search_disk_index --data_type uint8 --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_uint8_10D_10K_norm50.0_diskfull_oneshot --result_path /tmp/res --query_file ./rand_uint8_10D_10K_norm50.0.bin --gt_file ./l2_rand_uint8_10D_10K_norm50.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (sharded graph build, L2, no diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type uint8 --dist_fn l2 --data_path ./rand_uint8_10D_10K_norm50.0.bin --index_path_prefix ./disk_index_l2_rand_uint8_10D_10K_norm50.0_diskfull_sharded -R 16 -L 32 -B 0.00003 -M 0.00006
        ./build/tests/search_disk_index --data_type uint8 --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_uint8_10D_10K_norm50.0_diskfull_sharded --result_path /tmp/res --query_file ./rand_uint8_10D_10K_norm50.0.bin --gt_file ./l2_rand_uint8_10D_10K_norm50.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16
    - name: build and search disk index (one shot graph build, L2, diskPQ) 
      run: |   
        ./build/tests/build_disk_index --data_type uint8 --dist_fn l2 --data_path ./rand_uint8_10D_10K_norm50.0.bin --index_path_prefix ./disk_index_l2_rand_uint8_10D_10K_norm50.0_diskpq_oneshot -R 16 -L 32 -B 0.00003 -M 1 --PQ_disk_bytes 5
        ./build/tests/search_disk_index --data_type uint8 --dist_fn l2 --index_path_prefix ./disk_index_l2_rand_uint8_10D_10K_norm50.0_diskpq_oneshot --result_path /tmp/res --query_file ./rand_uint8_10D_10K_norm50.0.bin --gt_file ./l2_rand_uint8_10D_10K_norm50.0_self_gt100 --recall_at 5 -L 10 12 14 16 -W 2 --num_nodes_to_cache 10 -T 16


  ubuntu-18-build:
    runs-on: 'ubuntu-18.04'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install cmake g++ libaio-dev libgoogle-perftools-dev clang-format libboost-dev libboost-program-options-dev
        wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18487/l_BaseKit_p_2022.1.2.146.sh
        sudo sh l_BaseKit_p_2022.1.2.146.sh -a --components intel.oneapi.lin.mkl.devel --action install --eula accept -s
    - name: build
      run: |
        mkdir build && cd build && cmake .. && make -j
