name: Build and Release Python Wheels
on:
  release:
    types: [published]
jobs:
  python-release-wheels:
    name: Python
    uses: ./.github/workflows/build-python.yml
  release:
    runs-on: ubuntu-latest
    needs: python-release-wheels
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist/
      - name: Generate SHA256 files for each wheel
        run: |
          sha256sum dist/*.whl > checksums.txt
          cat checksums.txt
      - uses: actions/setup-python@v3
      - name: Install twine
        run: python -m pip install twine
      - name: Publish with twine
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*.whl
      - name: Update release with SHA256 and Artifacts
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.whl 
            checksums.txt
