name: Build and Release Python Wheels
on:
  release:
    types: [published]
jobs:
  build_wheels: 
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.3
      - name: build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: x86_64
      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl
  release:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: wheelhouse/
      - name: Generate SHA256 files for each wheel
        run: |
          sha256sum wheelhouse/*.whl > checksums.txt
          cat checksums.txt
      - uses: actions/setup-python@v3
      - name: Install twine
        run: python -m pip install twine
      - name: Publish with twine
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload wheelhouse/*.whl
      - name: Update release with SHA256 and Artifacts
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            wheelhouse/*.whl 
            checksums.txt
